# Generated by Django 4.2.13 on 2024-06-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie", name="director", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="movie", name="genre", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="movie", name="title", field=models.CharField(max_length=100),
        ),
    ]
